### ISSUE TITLE
Is this repo functioning / what is the status?

### ISSUE THREAD

**Issue by cdcv** [vishesh0123/FlashArbitrage---ETHernals#1]
Thank you for sharing this code.
Does it (or parts of it) currently work?
I want to be able to combine a loan with a 1inch swap for arb, and this is the only repo I've found that appears related to that.
Does your code create a flash loan and a 1inch swap in the same atomic transaction / same block?
BTW, one of the admins on the 1inch discord said that you can't call AggregationRouterV4 directly.  Seems like  if that's 
correct your code is going to have a problem?

**Comment by vishesh0123** [comment]
Still pending many things to add ..will try to complete it by this month
